# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-01 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20180429_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'All Subscriber'},
        ),
    ]
