# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.IntegerField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
