# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180529_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, default=None, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.IntegerField(default=None, max_length=10),
        ),
    ]
